name: flutter_todos
description: A new Flutter project.

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  meta: ^1.1.6
  equatable: ^1.0.0
  flutter_bloc: ^3.2.0
  flutter:
    sdk: flutter
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  path_provider: ^1.6.5
  http: ^0.12.1

dev_dependencies:
  hive_generator: ^0.7.0+2
  build_runner:

flutter:
  uses-material-design: true
